### ISSUE TITLE
 Power board fault short circuit problem 

### ISSUE THREAD

**Issue by wj7106** [greiginsydney/Intervalometerator#120]
Hi, I have a short circuit problem with the power supply board today. The power supply part of the whole PCB board is short circuited. After inspection, I found that the power supply board for raspberry pie 5V is short circuited, resulting in the short circuit of the whole system, including the solar MPPT controller. I removed the 12V to 5V power supply board, and the short circuit of the whole circuit disappears. Can I improve the PCB power supply part to avoid the short circuit of the whole system due to a module power failure?

**Comment by greiginsydney** [comment]
That's disappointing to hear. I hope you had heartbeating enabled and didn't lose too many images?

Was this a genuine Pololu supply, and were there any contributing factors like extreme heat or extreme over-current (e.g. by running a Pi 4 on the 500mA supply)? I chose the Pololu family at design time because I don't have the experience to design my own, and to date I've not had any fail.

I can't see any improvement you can make that will protect against such a fatal failure, other than adding a fuse. I don't know if a PTC device (like a PolySwitch) will help, as it will potentially add an upstream supply impedance into the regulator. Any outboard over-current limiter just adds another link into the chain and becomes another potential failure.

\- G.
