### ISSUE TITLE
Remote.it installs OK, but setup.sh fails with 'remoteit is not installed' & celery no longer starts

### ISSUE THREAD

**Issue by greiginsydney** [greiginsydney/Intervalometerator#144]
Remote.it installs OK:

![image](https://github.com/greiginsydney/Intervalometerator/assets/11004787/86c0fc2f-d1ca-4b0b-91b1-b3060c2e2ba0)

... but the install script doesn't detect it:

![image](https://github.com/greiginsydney/Intervalometerator/assets/11004787/0b7950da-e744-498c-9e15-560f1b867bc6)

The [remote.it] "connectd" service no longer exists.

Remote.it has changed their packaging for the Pi, and the "connectd.service has not existed for quite a while."

**Comment by greiginsydney** [comment]
![image](https://github.com/greiginsydney/Intervalometerator/assets/11004787/9f3ce190-dec2-4816-b303-0c03cf975738)

Celery *initially* fails to start, but does eventually.

**Comment by mmunsk** [comment]
Hi, does this mean that the intervalometerator doesn't work anymore? How does this affect its functionality?

**Comment by greiginsydney** [comment]
All good @mmunsk - turns out it's all good.

With its new install process, remote.it - and the intvlm8r - work fine, it's just that my previous fix is now redundant.

Because it all works so well I've not made it a priority to update the './setup test' code. Ta for the nudge.

\- G.

**Comment by mmunsk** [comment]
Hey Greig,
Quick question.
I'm setting up a camera far away.
If I needed to get heartbeats can I just have them sent to my email?
Or is this just for a website URL?

In any case how can I set this up to get these heartbeats and make sure the camera is working?

Thanks.



-------- Original message --------
From: Greig Sheridan ***@***.***>
Date: 2023-10-22 1:32 a.m. (GMT-06:00)
To: greiginsydney/Intervalometerator ***@***.***>
Cc: mmunsk ***@***.***>, Mention ***@***.***>
Subject: Re: [greiginsydney/Intervalometerator] Remote.it installs OK, but setup.sh fails with 'remoteit is not installed' & celery no longer starts (Issue #144)


All good @mmunsk<https://github.com/mmunsk> - turns out it's all good.

With its new install process, remote.it - and the intvlm8r - work fine, it's just that my previous fix is now redundant.

Because it all works so well I've not made it a priority to update the './setup test' code. Ta for the nudge.

- G.

**Comment by greiginsydney** [comment]
Check out the [setup-heartbeating.md](https://github.com/greiginsydney/Intervalometerator/blob/master/docs/setup-heartbeating.md) page. There's virtually nothing to do in the intvlm8r itself - it's all in the service you use. I've been using - and love - deadman's snitch.


\- G.
