### ISSUE TITLE
Use a background thread to copy files from the camera

### ISSUE THREAD

**Issue by greiginsydney** [greiginsydney/Intervalometerator#22]
The webUI will often crash with a [502 - Bad Gateway](https://github.com/greiginsydney/Intervalometerator/wiki/Troubleshooting#502---bad-gateway) error after initiating a "Copy now" request from the /Transfer page. The more images there are to copy, the greater the likelihood of this occurring. (This also takes each time the Pi is started and on a schedule if the user has created a cron job).

The issue is that "copy_files(camera)" in [intvlm8r.py](https://github.com/greiginsydney/Intervalometerator/blob/master/Raspberry%20Pi/intvlm8r.py)  holds the script in a loop until it's finished copying, and if there are a lot of images Gunicorn will eventually time out.

The (a?) fix will be to re-write copy_files so it runs as a background task.

The camera will still be busy for the duration, but the rest of the web UI will run OK, and the camera's non-availability will be flagged with a ["Could not claim the USB device"](https://github.com/greiginsydney/Intervalometerator/wiki/Troubleshooting#could-not-claim-the-usb-device) error.

Any takers?

**Comment by FernandaRamosTL** [comment]
Dear Greig, good afternoom. My name is Fernanda, and I am a time-lapse artist based in Rio. I have been wondering for a long time on how to build my own intervalometer, and I must congratulate you for your job. I will follow your tutorials and try to build the intervalometer. I use some other solutions for my comercial work. You can see my films at jugularfilmes.com
Dear Greig: I believe that this problem is due to the amount of data at the camera memory card. The best thing to do is if after the pictures are transfered to PI, they are deleted from the camera. Do you think you can improve the code to do it? Delete the images once a day, and the problem should be gone. I know from personal experience that many files on the camera make the comunication via USB very dificult. I am not a programer, I am just a filmmaker who is making animation with photos and timelapse films since 1997, but even when you connect windows or mac to a camera with many many files it is very very dificult to copy it to the computer.
Well, I would love to know you better. Please visit my website and drop me an email if you want to be in touch.

**Comment by FernandaRamosTL** [comment]
Hi, I sent you a message at linked in.

**Comment by greiginsydney** [comment]
Fixed in release [v4.0.0](https://github.com/greiginsydney/Intervalometerator/releases/tag/v4.0.0) with the addition of Celery & Redis.
