### ISSUE TITLE
 Interval problem 

### ISSUE THREAD

**Issue by wj7106** [greiginsydney/Intervalometerator#78]
I added a lot of interval time in the interval setting page program, and there was an interval problem. For example, when I set a seven minute interval, the next hour, three minutes plus seven minutes should be 10 minutes, then it becomes 07 minutes, and it becomes the minutes before the automatic reset, starting from the seven minutes set

**Comment by greiginsydney** [comment]
I see what's going on here, and it's because you've chosen a custom interval that's not divisible by 60.

In the Arduino's "setAlarm1()" function it holds in a loop, adding a minute to the current time (the minute count) over and over until the number becomes divisible by <interval>. If the number is > 60 it subtracts 60 and increments the hour. This becomes the time for the next shot, and the alarm is set.

So as you reach the end of the first hour, it will fire at minutes = 56 and keep incrementing until minutes = 63, then subtract 60, so the first photo in the next hour will be at 3 minutes past. When that photo is taken it will repeat the process and re-sync, with another photo at 7 minutes past.
